Namespace(withAug=True, AugDirect=20, method_name='SymDiGCN', seed=100, GPUdevice=0, IsDirectedData=True, dataset='dgl/cora', undirect_dataset='CiteSeer', MakeImbalance=True, CustomizeMask=False, K=2, heads=8, log_root='../logs/', log_path='test', data_path='../dataset/data/tmp/', epochs=1500, num_filter=2, p_q=0.95, p_inter=0.1, dropout=0.0, debug=False, new_setting=False, layer=2, lr=0.005, l2=0.0005, to_undirected=False, alpha=0.1, randomseed=-1, imb_ratio=100, n_layer=2, feat_dim=64, warmup=5, epoch=900, tau=2, max=False, no_mask=False, gdc='ppr')
0
cuda:0
excel_file_path is  TrueAug_SymDiGCN_cora_output.xlsx
12-19-21:17:11
dataset is  dgl cora
  NumNodes: 2708
  NumEdges: 5278
  NumFeats: 1433
  NumClasses: 7
  NumTrainingSamples: 140
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.
Dataset is  Dataset("cora_v2", num_graphs=1, save_path=/home/qj2004/.dgl/cora_v2_d697a464) 
Chosen from DirectedData:  True
Traceback (most recent call last):
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 597, in <module>
    main(args)
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 87, in main
    data = data.to(device)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/heterograph.py", line 5709, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/heterograph_index.py", line 255, in copy_to
    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
  File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [21:17:11] /opt/dgl/src/runtime/c_runtime_api.cc:82: Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl.
Stack trace:
  [bt] (0) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x75) [0x7fc3480d58f5]
  [bt] (1) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::runtime::DeviceAPIManager::GetAPI(std::string, bool)+0x202) [0x7fc348444d82]
  [bt] (2) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::runtime::DeviceAPI::Get(DGLContext, bool)+0x1e1) [0x7fc348441361]
  [bt] (3) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DGLDataType, DGLContext)+0x13b) [0x7fc34845c83b]
  [bt] (4) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DGLContext const&) const+0xc3) [0x7fc348497043]
  [bt] (5) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0x3ff) [0x7fc3485a453f]
  [bt] (6) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(dgl::HeteroGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DGLContext const&)+0xf6) [0x7fc3484a38c6]
  [bt] (7) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(+0x51b686) [0x7fc3484b2686]
  [bt] (8) /home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/dgl/libdgl.so(DGLFuncCall+0x48) [0x7fc348440598]


