Namespace(withAug=True, AugDirect=20, method_name='APPNP', seed=100, GPUdevice=2, IsDirectedData=True, dataset='WikipediaNetwork/squirrel', undirect_dataset='Cora', MakeImbalance=True, CustomizeMask=False, K=2, heads=8, log_root='../logs/', log_path='test', data_path='../dataset/data/tmp/', epochs=1500, num_filter=2, p_q=0.95, p_inter=0.1, dropout=0.0, debug=False, new_setting=False, layer=2, lr=0.005, l2=0.0005, to_undirected=False, alpha=0.1, randomseed=-1, imb_ratio=100, n_layer=2, feat_dim=64, warmup=5, epoch=900, tau=2, max=False, no_mask=False, gdc='ppr')
CUDA Device Index: 2
12-21-14:42:42
excel_file_path is  TrueAug_APPNP_WikipediaNetworksquirrel12-21-14:42:42_dir.xlsx
dataset is  WikipediaNetwork squirrel
Dataset is  WikipediaNetwork() 
Chosen from DirectedData:  True
Num of bidrected edges: 18580, total num of edges: 217073
This is directed graph:  True
data_x torch.Size([5201, 2089])
splits 10
APPNP_ModelBen(
  (line1): Linear(in_features=2089, out_features=2, bias=True)
  (line2): Linear(in_features=2, out_features=2, bias=True)
  (conv1): APPNP(K=10, alpha=0.1)
  (conv2): APPNP(K=10, alpha=0.1)
  (Conv): Conv1d(2, 5, kernel_size=(1,), stride=(1,))
)
Beginning for split:  0 21-14:45:21
Traceback (most recent call last):
  File "/home/qj2004/Ben/magnet/src/GNNChangeTrainTest.py", line 386, in main
    out = model(new_x, new_SparseEdges, new_edge_weight)  #
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: APPNP_ModelBen.forward() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qj2004/Ben/magnet/src/GNNChangeTrainTest.py", line 595, in <module>
    main(args)
  File "/home/qj2004/Ben/magnet/src/GNNChangeTrainTest.py", line 389, in main
    out = model(new_x, new_edge_index)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qj2004/Ben/magnet/src/layer/geometric_baselines.py", line 586, in forward
    x = self.Conv(x)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 307, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 303, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
