cuda:0
Namespace(withAug=True, AugDirect=20, method_name='GIN', seed=100, IsDirectedData=True, dataset='WikipediaNetwork/squirrel', undirect_dataset='CiteSeer', MakeImbalance=True, CustomizeMask=False, heads=8, log_root='../logs/', log_path='test', data_path='../dataset/data/tmp/', epochs=1500, num_filter=2, p_q=0.95, p_inter=0.1, dropout=0.0, debug=False, new_setting=False, layer=2, lr=0.005, l2=0.0005, to_undirected=False, alpha=0.1, randomseed=-1, imb_ratio=100, n_layer=2, feat_dim=64, warmup=5, epoch=900, tau=2, max=False, no_mask=False, gdc='ppr')
dataset is  WikipediaNetwork
Dataset is  WikipediaNetwork() 
Chosen from DirectedData:  True
Num of bidrected edges: 18580, total num of edges: 217073
This is directed graph:  True
data_x torch.Size([5201, 2089])
splits 10
0
Traceback (most recent call last):
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 334, in main
    out = model(new_x, new_SparseEdges, new_edge_weight)  #
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: GIN_ModelBen.forward() takes 3 positional arguments but 4 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 480, in <module>
    main(args)
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 337, in main
    out = model(new_x, new_edge_index)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qj2004/magnet/src/layer/geometric_baselines.py", line 623, in forward
    x = self.conv1(x, edge_index)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch_geometric/nn/conv/gin_conv.py", line 84, in forward
    out = out + (1 + self.eps) * x_r
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
