cuda:0
Namespace(withAug=True, AugDirect=20, method_name='SymDiGCN', seed=100, IsDirectedData=False, dataset='WebKB/texas', undirect_dataset='CiteSeer', MakeImbalance=True, CustomizeMask=False, K=2, heads=8, log_root='../logs/', log_path='test', data_path='../dataset/data/tmp/', epochs=1500, num_filter=2, p_q=0.95, p_inter=0.1, dropout=0.0, debug=False, new_setting=False, layer=2, lr=0.005, l2=0.0005, to_undirected=False, alpha=0.1, randomseed=-1, imb_ratio=100, n_layer=2, feat_dim=64, warmup=5, epoch=900, tau=2, max=False, no_mask=False, gdc='ppr')
excel_file_path is  TrueAug_SymDiGCN_CiteSeer_output.xlsx
12-07-21:26:18
Dataset is  CiteSeer() 
Chosen from DirectedData:  False
Num of bidrected edges: 4552, total num of edges: 9104
This is directed graph:  False
data_x torch.Size([3327, 3703])
cuda:0
0
mu  cpu cpu
cuda:0
Traceback (most recent call last):
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 393, in main
    out = model(new_x, new_SparseEdges, new_edge_weight)  #
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: SymModel.forward() missing 3 required positional arguments: 'in_w', 'edge_out', and 'out_w'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 396, in main
    out = model(new_x, new_edge_index)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: SymModel.forward() missing 4 required positional arguments: 'edge_in', 'in_w', 'edge_out', and 'out_w'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 596, in <module>
    main(args)
  File "/home/qj2004/magnet/src/GNNChangeTrainTest.py", line 398, in main
    out= model(new_x)
  File "/home/qj2004/.conda/envs/myenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: SymModel.forward() missing 5 required positional arguments: 'edge_index', 'edge_in', 'in_w', 'edge_out', and 'out_w'
